baseURL = "https://medea.netlify.com/"
languageCode = "es-es"
title = "Proyecto MEDEA 3"
theme = "kube"
description = "Web del proyecto de investigación Desigualdades socioeconómicas y medioambientales en la distribución geográfica de la mortalidad en grandes ciudades de España (1996-2015)"
Paginate = 4
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "\\.Rproj$"]
disqusShortname = "medea-1"
enableEmoji = true

[author]
  name = "carlosvergara"
[params]
  RSSLink = "/index.xml"
  author = "MEDEA" # add your company name
  github = "" # add your github profile name
  twitter = "medeaproj" # add your twitter profile
  email = "correo@electronico.com"
  highlight_languages = ["r", "cpp", "sql", "bash", "tex"]
  sharing = true

[[menu.main]]
    name = "Blog"
    weight = 1
    url = "/blog/"
[[menu.main]]
    name = "Documentos"
    weight = 2
    url = "/docs/"
[[menu.main]]
    name = "Software"
    weight = 3
    url = "/software/"
[[menu.main]]
    name = "Sobre nosotros"
    weight = 4
    url = "/about/"
[[menu.main]]
    name = "Contacto"
    weight = 5
    url = "/contact/"
[[menu.main]]
    name = "Faq"
    weight = 6
    url = "/faq/"
